"use client"

import { PenLine, Sparkles, Users } from "lucide-react"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"

export function BookshelfLegendChipSources() {
  return (
    <TooltipProvider delayDuration={300}>
      <span className="flex items-center gap-1.5 text-[10px] text-muted-foreground/80">
        Chip:
        <Tooltip>
          <TooltipTrigger asChild>
            <span className="inline-flex cursor-default items-center gap-0.5 rounded px-0.5 hover:text-muted-foreground">
              <PenLine className="h-3 w-3" aria-hidden />
              Author
            </span>
          </TooltipTrigger>
          <TooltipContent side="bottom" className="max-w-[220px]">
            Content warnings from the author or publisher (e.g. author’s website or provided list).
          </TooltipContent>
        </Tooltip>
        <span className="text-muted-foreground/60">·</span>
        <Tooltip>
          <TooltipTrigger asChild>
            <span className="inline-flex cursor-default items-center gap-0.5 rounded px-0.5 hover:text-muted-foreground">
              <Sparkles className="h-3 w-3" aria-hidden />
              AI
            </span>
          </TooltipTrigger>
          <TooltipContent side="bottom" className="max-w-[220px]">
            Content warnings generated by Subtext’s AI analysis of the book.
          </TooltipContent>
        </Tooltip>
        <span className="text-muted-foreground/60">·</span>
        <Tooltip>
          <TooltipTrigger asChild>
            <span className="inline-flex cursor-default items-center gap-0.5 rounded px-0.5 hover:text-muted-foreground">
              <Users className="h-3 w-3" aria-hidden />
              Community
            </span>
          </TooltipTrigger>
          <TooltipContent side="bottom" className="max-w-[220px]">
            Content warnings submitted or voted on by the community.
          </TooltipContent>
        </Tooltip>
      </span>
    </TooltipProvider>
  )
}
