import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ArrowLeft } from "lucide-react"

export const metadata = {
  title: 'Terms of Service | Subtext',
  description: 'Terms of Service for Subtext - Book Content Warnings',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-16 max-w-4xl">
        {/* Header */}
        <div className="mb-12">
          <Link href="/">
            <Button variant="ghost" className="mb-6 text-muted-foreground hover:text-foreground">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Home
            </Button>
          </Link>
          <h1 className="font-serif text-4xl md:text-5xl font-medium tracking-tight text-foreground mb-4">
            Terms of Service
          </h1>
          <p className="text-sm text-muted-foreground italic">
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
        </div>

        {/* Content */}
        <div className="prose prose-sm max-w-none space-y-8 text-muted-foreground leading-relaxed">
          <section>
            <h2 className="font-serif text-2xl text-foreground mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Subtext ("the Service"), you agree to be bound by these Terms of Service ("Terms"). 
              If you do not agree to these Terms, you may not use the Service.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-foreground mb-4">2. Description of Service</h2>
            <p>
              Subtext is a book analysis application that provides content warnings, age ratings, and thematic information 
              for books. The Service uses artificial intelligence to analyze book descriptions and metadata from publicly 
              available sources to generate content warnings.
            </p>
            <p className="mt-4">
              <strong className="text-foreground">Important:</strong> Content warnings are generated by AI and are 
              indicative only. Age ratings follow Australian Classification Board methodology but are not official ratings 
              from any classification board. Severity ratings are subjective and may vary based on individual sensitivity 
              and interpretation.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-foreground mb-4">3. Use of Service</h2>
            <p>You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to:</p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li>Use the Service to violate any applicable laws or regulations</li>
              <li>Attempt to reverse engineer, decompile, or disassemble any part of the Service</li>
              <li>Interfere with or disrupt the Service or servers connected to the Service</li>
              <li>Use automated systems to access the Service in a manner that sends more requests than a human could reasonably produce</li>
              <li>Reproduce, duplicate, copy, sell, or exploit any portion of the Service without express written permission</li>
            </ul>
            <p className="mt-4">
              <strong className="text-foreground">Rate Limiting:</strong> The Service implements rate limiting to ensure 
              fair usage and manage costs. Anonymous users are limited to 5 scans per IP address per day. Rate limits reset 
              daily at midnight. We reserve the right to adjust rate limits at any time.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-foreground mb-4">4. Content Warnings and Accuracy</h2>
            <p>
              Content warnings provided by the Service are generated using artificial intelligence and are based on 
              publicly available book descriptions and metadata. While we strive for accuracy, the Service makes no 
              guarantees about the completeness, accuracy, or reliability of content warnings.
            </p>
            <p className="mt-4">
              <strong className="text-foreground">You acknowledge that:</strong>
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li>Content warnings may contain errors or omissions</li>
              <li>Severity ratings are subjective and may not reflect your personal sensitivity</li>
              <li>Some content warnings may contain spoilers about plot elements</li>
              <li>The Service is not affiliated with any official classification board</li>
              <li>You should use your own judgment when selecting books to read</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-foreground mb-4">5. Intellectual Property</h2>
            <p>
              The Service, including its original content, features, and functionality, is owned by Subtext and is 
              protected by international copyright, trademark, and other intellectual property laws.
            </p>
            <p className="mt-4">
              Book metadata, descriptions, and cover images displayed in the Service are sourced from third-party 
              providers (such as Google Books and Open Library) and are subject to their respective terms of service 
              and copyright protections.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-foreground mb-4">6. Third-Party Services</h2>
            <p>
              The Service uses third-party services and APIs, including but not limited to:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li><strong className="text-foreground">Google Books API:</strong> Used to fetch book metadata and descriptions</li>
              <li><strong className="text-foreground">Open Library:</strong> Used as an alternative source for book information</li>
              <li><strong className="text-foreground">Google Custom Search API:</strong> Used to enrich book descriptions when needed</li>
              <li><strong className="text-foreground">OpenAI API:</strong> Used for AI-powered content analysis</li>
              <li><strong className="text-foreground">Google Gemini API:</strong> Used for multi-model content analysis</li>
            </ul>
            <p className="mt-4">
              Your use of the Service may be subject to the terms of service of these third-party providers. 
              We are not responsible for the availability, accuracy, or content of third-party services.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-foreground mb-4">7. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR 
              IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR 
              PURPOSE, OR NON-INFRINGEMENT.
            </p>
            <p className="mt-4">
              We do not warrant that the Service will be uninterrupted, secure, or error-free, or that defects will be 
              corrected. We do not warrant that the content warnings provided are accurate, complete, or suitable for 
              your purposes.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-foreground mb-4">8. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, SUBTEXT SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, 
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY 
              OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR USE 
              OF THE SERVICE.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-foreground mb-4">9. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Subtext, its officers, directors, employees, and agents from any 
              claims, damages, losses, liabilities, and expenses (including legal fees) arising out of or relating to 
              your use of the Service or violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-foreground mb-4">10. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of any material changes by 
              posting the new Terms on this page and updating the "Last updated" date. Your continued use of the Service 
              after such changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-foreground mb-4">11. Termination</h2>
            <p>
              We reserve the right to terminate or suspend your access to the Service at any time, with or without 
              cause or notice, for any reason, including violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-foreground mb-4">12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which 
              Subtext operates, without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-foreground mb-4">13. Contact Information</h2>
            <p>
              If you have any questions about these Terms, please contact us through the Service or visit our 
              <Link href="/transparency" className="text-primary hover:underline"> transparency page</Link>.
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="mt-16 pt-8 border-t border-border">
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/">
              <Button variant="outline" className="w-full sm:w-auto">
                Back to Home
              </Button>
            </Link>
            <Link href="/privacy">
              <Button variant="outline" className="w-full sm:w-auto">
                Privacy Policy
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </main>
  )
}

