/**
 * Glossary of terms used in content warnings
 * Provides neutral, descriptive definitions for romance/BookTok terminology
 * and all taxonomy categories/subcategories
 * 
 * Most entries are auto-generated from taxonomy-v2.ts
 * Some entries have enhanced descriptions for BookTok/romance-specific terms
 */

export const GLOSSARY: Record<string, string> = {
  // Romance/BookTok Terms (enhanced descriptions)
  "CNC": "Consensual Non-Consent: Sexual roleplay involving agreed-upon scenarios of force or lack of consent, negotiated beforehand.",
  "Dub-Con": "Dubious Consent: Situations where consent is unclear, compromised (e.g., intoxication), or influenced by pressure/power dynamics.",
  "Non-Con": "Non-Consensual: Depictions of sexual acts occurring without consent. In Dark Romance, this is often a plot device or character dynamic.",
  "Dark Romance": "A sub-genre of romance dealing with taboo, heavy, or morally grey themes, often involving anti-heroes or villainous love interests.",
  
  // Taxonomy Categories & Subcategories (auto-generated from taxonomy-v2.ts)
  "Ableism": "Ableism, discrimination against disabilities, disability slurs.",
  "Academic Pressure / Exam Stress": "Academic pressure, exam stress, academic competition, or intense educational pressure. May include academic failure, grade anxiety, or competitive academic environments.",
  "Acephobia": "Discrimination against asexual people, invalidation of asexuality, or pressure to be sexual.",
  "Addiction": "Addiction, substance dependence, substance use disorder.",
  "Alcohol": "Alcohol consumption, drinking, alcohol abuse.",
  "Ambiguous or Non-Explicit Consent (Dub-Con)": "Consent is unclear, negotiated implicitly, or framed as resistance/desire tension. Also known as \"Dub-Con\" in dark romance.",
  "Animal Cruelty": "Animal cruelty, harm to animals, animal death, pet death.",
  "Animal Death": "Animal death, pet death, or harm to animals.",
  "Antisemitism": "Antisemitism, anti-Jewish discrimination, or Jewish stereotypes.",
  "Anxiety": "Anxiety, panic attacks, stress, anxiety disorders.",
  "BDSM Themes": "Power exchange, dominance/submission, or restraint themes. BDSM stands for Bondage, Discipline, Dominance, Submission, Sadism, and Masochism.",
  "Biphobia": "Discrimination against bisexual people, biphobic stereotypes, or invalidation of bisexuality.",
  "Blood / Hemophobia": "Blood, gore, or blood-related medical content.",
  "Body Horror": "Body horror, extreme body modification, or graphic body-related content.",
  "Breeding Kink": "Sexual focus on impregnation, breeding, or pregnancy as kink. Distinct from actual pregnancy/childbirth.",
  "Bullying": "Bullying, harassment, intimidation.",
  "Bullying / Social Cruelty": "Bullying, hazing, public humiliation, or intense social pressure.",
  "Cancer": "Cancer, cancer treatment, or cancer-related illness.",
  "Cannibalism": "Cannibalism, eating human flesh, or cannibalistic themes.",
  "Car Accidents / Crashes": "Car crashes, plane crashes, or severe vehicle accidents.",
  "Casual Suicidal Ideation / Jokes": "Non-graphic but repeated \"jokes\" or casual references to suicide, self-harm, or death wishes. Less severe than acute suicidal content but may still be triggering.",
  "Character Death": "Character deaths, on-page deaths, death scenes.",
  "Cheating": "Infidelity, cheating in relationships, betrayal.",
  "Chronic Illness": "Chronic illness, disability, or long-term health conditions.",
  "Classism / Poverty": "Discrimination based on class, extreme poverty, homelessness, or economic status discrimination.",
  "Coarse Language": "Strong language, swearing, or slurs.",
  "Consensual Non-Consent (CNC)": "Consensual non-consent, CNC play, or negotiated non-consent scenarios. Distinct from actual non-consent.",
  "Controlling Behavior": "Controlling relationships, possessiveness, isolation.",
  "Cult Dynamics": "Cult dynamics, indoctrination, or cult manipulation.",
  "Cultural Appropriation / Colonial Themes": "Cultural appropriation, colonial themes, exploitation of Indigenous or marginalized cultures, or problematic representation of cultural groups.",
  "Darkness / Nyctophobia": "Darkness, being in the dark, or fear of the dark.",
  "Death / Grief": "Character deaths, terminal illness, mourning, or funeral scenes.",
  "Deception / Secrets": "Deception, lying, or secret-keeping involving friends or family (e.g., hiding relationship status, lying to friends, keeping secrets from loved ones).",
  "Degradation / Humiliation": "Sexual content involving humiliation, degradation, or verbal diminishment.",
  "Dental Trauma": "Dental procedures, teeth falling out, pulling teeth, or dental gore.",
  "Depression": "Depression, mood disorders, depressive episodes.",
  "Discrimination": "Racism, sexism, homophobia, transphobia, or other forms of hate speech/discrimination.",
  "Disordered Eating": "Disordered eating, eating disorders, body image issues.",
  "Divorce / Separation": "Divorce, separation, or relationship breakdown. Moved from Death / Grief to better reflect family dynamics context.",
  "Domestic Violence": "Domestic violence, intimate partner violence, family violence.",
  "Drug Use": "Drug use, drug abuse, illegal substances.",
  "Economic Collapse / Eviction / Job Loss": "Economic collapse, eviction, foreclosure, job loss, or sudden economic hardship. Distinct from chronic poverty. Keywords: recession, foreclosure, redundancy, layoffs.",
  "Emotional Abuse": "Emotional abuse, verbal abuse, psychological abuse.",
  "Emotional Abuse / Toxic Relationships": "Gaslighting, manipulation, controlling behavior, or toxic relationship dynamics.",
  "Enclosed Spaces / Claustrophobia": "Enclosed spaces, claustrophobia, being trapped, or confinement.",
  "Excommunication / Religious Exclusion": "Excommunication, religious exclusion, or religious shunning.",
  "Exhibitionism / Voyeurism": "Sexual content involving being watched or watching.",
  "Explicit Sexual Content": "Explicit sexual scenes, graphic sexual descriptions.",
  "Family Dynamics": "Family-related trauma, abandonment, or family system issues.",
  "Fatphobia / Body Shaming": "Discrimination based on weight, body shaming, anti-fat bias, or cruelty toward fat characters.",
  "Financial Abuse": "Financial abuse, economic control, or financial manipulation.",
  "Foster Care / Adoption Trauma": "Foster care trauma, adoption breakdown, or displacement of children.",
  "Funeral Scenes": "Funeral scenes, death rituals, memorial services.",
  "Gaslighting": "Gaslighting, psychological manipulation, making someone question their reality.",
  "Gendered Sexual Degradation": "Sexually degrading language targeting women or gendered characters.",
  "Graphic Violence": "Graphic violence, gore, detailed violence, blood.",
  "Grief": "Grief, mourning, loss, bereavement.",
  "Grief Processing": "Detailed grief processing, mourning, or loss processing.",
  "Grooming": "Grooming, predatory behavior, or manipulation of vulnerable individuals (often in age-gap or power imbalance contexts).",
  "Hazing": "Hazing, initiation rituals, forced participation.",
  "Heights / Falling": "Heights, falling, vertigo, or high places.",
  "Homophobia": "Homophobia, anti-LGBTQ+ content, discrimination against gay/lesbian people.",
  "Human Trafficking": "Human trafficking, sex trafficking, or forced servitude. Distinct from general kidnapping.",
  "Incest / Pseudo-Incest": "Incest, pseudo-incest (step-siblings), or blood relation sexual/romantic content.",
  "Infanticide / Intentional Harm to a Child": "Infanticide, attempted murder of a newborn/child, or intentional harm targeting infants/children (distinct from accidental harm or general peril).",
  "Infertility": "Infertility, long-term lack of conception, or inability to conceive. Distinct from pregnancy loss.",
  "Infidelity / Cheating": "Infidelity, cheating in relationships, or sexual/romantic betrayal. Also see Emotional Abuse category for relationship dynamics.",
  "Intense Romance / Spice": "Intense romantic/sexual tension, steamy scenes, explicit romance/spice content. Note: Emotional romantic tension alone may not require a warning.",
  "Islamophobia": "Islamophobia, anti-Muslim discrimination, or Muslim stereotypes.",
  "Kidnapping / Confinement": "Kidnapping, abduction, confinement, being held against will, captivity.",
  "Knife Play / Blood Play": "Sexualized use of knives, blood play, or weapon play in sexual contexts.",
  "Lesbophobia": "Discrimination specifically against lesbians or lesbian relationships.",
  "Manipulation": "Manipulative behavior, emotional manipulation, coercive control.",
  "Medical / Health": "Medical procedures, health conditions, infertility, or medical trauma.",
  "Medical Detail / Procedural": "Non-graphic surgery or medical procedures without trauma focus. Clinical or procedural medical content.",
  "Medical Procedures": "Surgery, medical procedures, hospital scenes, or medical trauma.",
  "Mental Health": "Depression, anxiety, suicide, eating disorders, and other mental health themes.",
  "Miscarriage / Abortion": "Miscarriage, stillbirth, abortion, pregnancy loss.",
  "Misgendering / Deadnaming": "Misgendering, deadnaming, or use of incorrect pronouns for transgender or non-binary characters.",
  "Natural Disasters": "Natural disasters, environmental trauma, or climate-related events.",
  "Near Death": "Near-death experiences, life-threatening situations.",
  "Needles / Medical Procedures": "Needles, injections, medical procedures, or blood draws.",
  "Non-Violent Crime / Prison": "General crime content: robbery, non-violent crime, prison/jail settings, interrogations, or criminal justice system themes. May be tagged even when violence is mild. Keywords: heist, robbery, prison setting, courtroom drama.",
  "Occult / Supernatural": "Occult themes, supernatural elements, or dark magic.",
  "Other": "Other potentially triggering content.",
  "Other Death / Grief": "Other death/grief-related content not covered by specific subcategories.",
  "Other Discrimination": "Other forms of discrimination not covered by specific subcategories.",
  "Other Family Dynamics": "Other family-related trauma or dynamics not covered above.",
  "Other Language": "Other language-related content not covered by specific subcategories.",
  "Other Medical / Health": "Other medical or health-related content not covered above.",
  "Other Mental Health": "Other mental health themes not covered by specific subcategories.",
  "Other Phobias": "Other specific phobias or fear triggers not covered above.",
  "Other Religious / Cult": "Other religious or cult-related content not covered above.",
  "Other Sexual Content": "Other sexual content not covered by specific subcategories.",
  "Other Social Cruelty": "Other forms of social cruelty not covered by specific subcategories.",
  "Other Substance Use": "Other substance-related content not covered by specific subcategories.",
  "Other Toxic Relationships": "Other toxic relationship dynamics not covered by specific subcategories.",
  "Other Violence": "Other forms of violence not covered by specific subcategories.",
  "Overdose": "Overdose, drug-related medical emergencies, poisoning.",
  "Pandemics / Contagion": "Pandemics, plague, outbreaks, contagion narratives, or infectious disease themes. Common post-2020 trigger. Keywords: plague, outbreak, virus, lockdown.",
  "Parental Abandonment": "Parental abandonment, estrangement, or parents leaving.",
  "Past Death": "Past deaths (discussed but not shown), historical deaths.",
  "Phobias / Specific Fears": "Specific phobias or fear triggers that may cause anxiety or panic.",
  "Physical Violence": "Physical fighting, combat, brawls, physical altercations.",
  "Plastic Surgery / Cosmetic Procedures": "Plastic surgery, cosmetic procedures, or elective body modification. Distinct from body horror and general medical trauma.",
  "Police Brutality / State Violence": "Police brutality, state violence, or systemic violence by authorities.",
  "Pornography / Sex Work": "Explicit pornography, sex work representation, or sexual content industry themes.",
  "Possessive or Obsessive Dynamics": "Sexual or romantic framing involving ownership, obsession, or control.",
  "Power Imbalance": "Sexual or romantic dynamics involving authority, dependency, or unequal power (e.g., boss/employee, teacher/student, age gaps).",
  "Pregnancy / Childbirth": "Pregnancy, childbirth, pregnancy complications, or pregnancy-related trauma.",
  "Pregnancy Loss": "Miscarriage, stillbirth, or pregnancy loss. Distinct from infertility (long-term conception issues).",
  "Primal Play": "Hunting/chasing dynamics, primal kink, or \"touch her and you die\" tropes in sexual/romantic contexts.",
  "PTSD / Trauma": "Post-traumatic stress disorder, trauma, traumatic experiences.",
  "Public Humiliation": "Public humiliation, shaming, embarrassment.",
  "Purity / Virginity Framing": "Sexual value tied to virginity, purity, or sexual restraint.",
  "Queer Joy / Identity Focus": "Non-triggering identity flags: coming out arcs, transition journeys, or positive LGBTQ+ identity exploration. Not discrimination, but identity-focused content that some readers seek or avoid. Keywords: coming out arc, transition journey, found family (queer).",
  "Queerphobia": "General anti-queer sentiment, queerphobic language, or discrimination against LGBTQ+ people.",
  "Racism": "Racism, racial discrimination, racial slurs.",
  "Religious / Cult Content": "Religious trauma, cult dynamics, occult themes, or religious persecution.",
  "Religious Discrimination": "Religious discrimination, religious intolerance, religious persecution.",
  "Religious Joy / Positive Identity": "Non-triggering identity flags: positive religious identity exploration, faith journeys, or affirming religious content. Not discrimination, but identity-focused content that some readers seek or avoid. Keywords: faith journey, religious community, spiritual growth.",
  "Religious Trauma": "Religious trauma, religious abuse, or religious-based harm.",
  "School Shootings / Mass Violence": "School shootings, mass shootings, or mass violence events.",
  "Self-Harm": "Self-harm behaviors, cutting, non-suicidal self-injury.",
  "Sexism": "Sexism, gender discrimination, misogyny, misandry.",
  "Sexual Coercion / Pressure": "Emotional pressure, manipulation, or obligation leading to sexual activity.",
  "Sexual Content": "Sexual situations, explicit content, sexual violence, or intense romance.",
  "Sexual Roleplay": "Sexual roleplay scenarios as part of intimacy.",
  "Sexual Shaming Language": "Language that shames or devalues characters for sexual behaviour.",
  "Sexual Themes": "Sexual themes, discussions, references (non-explicit).",
  "Sexual Violence": "Sexual assault, rape, non-consensual sexual content.",
  "Slurs": "Slurs, hate speech, derogatory language.",
  "Snakes / Serpents": "Snakes, serpents, or snake-like creatures.",
  "Social Pressure": "Intense social pressure, peer pressure, conformity pressure.",
  "Somnophilia / Sleep Play": "Non-consensual or dub-consensual sexual acts while one partner is sleeping or unconscious.",
  "Spiders / Arachnids": "Spiders, arachnids, or spider-like creatures.",
  "Stalking": "Stalking, obsessive following, or unwanted surveillance.",
  "Strong Language": "Strong language, profanity, swearing.",
  "Substance Use": "Alcohol consumption, drug use, addiction, or overdose.",
  "Suicidal Ideation": "Suicidal thoughts, attempts, detailed descriptions of suicide.",
  "Suicide of a Minor": "Suicide or suicidal ideation involving a child or minor character.",
  "Taboo or Fetish Themes": "Fetish-focused sexual framing outside mainstream romance norms.",
  "Terminal Illness": "Terminal illness, dying characters, end-of-life care.",
  "Torture": "Torture, extreme violence, prolonged suffering.",
  "Toxic Friendships": "Toxic friendships, unhealthy social dynamics, peer pressure.",
  "Transphobia": "Transphobia, anti-trans content, discrimination against transgender people.",
  "Trypophobia": "Clusters of small holes, patterns, or trypophobia triggers.",
  "Violence": "Physical violence, fighting, weapons, war, or gore.",
  "Violence Against Children": "Violence directed at children, child abuse, harm to minors. Implicitly covers suicidal content involving minors (see also: suicide_minor for explicit tagging).",
  "Vomiting / Emetophobia": "Vomiting, nausea, or scenes depicting sickness.",
  "War": "War, military violence, battle scenes, combat.",
  "Water / Drowning": "Water, drowning, deep water, or aquaphobia triggers.",
  "Weapons": "Weapons, gun violence, knife violence, weapon use.",
  "Weight Loss / Dieting Focus": "Chronic diet talk, weight loss focus, \"makeover\" plots, or dieting narratives. Distinct from disordered eating but may be triggering for ED-sensitive readers. Keywords: makeover, diet culture, clean eating.",
  "Workplace Burnout / Toxic Workplace": "Workplace burnout, toxic work environments, overwork, or professional stress. May include exploitation, harassment, or unsafe working conditions.",
};

/**
 * Get a glossary definition for a term
 * Returns the definition if found, or null if not in glossary
 */
export function getGlossaryDefinition(term: string): string | null {
  return GLOSSARY[term] || null;
}

/**
 * Check if a term has a glossary definition
 */
export function hasGlossaryDefinition(term: string): boolean {
  return term in GLOSSARY;
}
